name: Rust Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (x86_64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Packages
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Calculate checksums
        run: |
          cd target/release
          sha512sum redlib-ex > redlib.sha512
          sha256sum redlib-ex > redlib.sha256

      - uses: actions/upload-artifact@v4
        name: Upload Build Artifact
        with:
          name: redlib-ex
          path: |
            target/release/redlib-ex
            target/release/redlib.sha512
            target/release/redlib.sha256